version: "3.8"
services:
  client:
    image: kh2fm-randomizer:local
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./randomizer:/randomizer